[project]
name = "notify-line-to-aws-billing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "cfn-lint>=1.20.1",
]
